### ISSUE TITLE
Bug with Congrats 

### ISSUE THREAD

**Issue by francineloza** [francineloza/HIM_Operations#76]
sending congrats
staring round of congrats
failed recharge sms: []
num sent recharge sms: 4
Congratulatory_message_control.wav
Traceback (most recent call last):
 File "/bbkinghome/nedmonds/Haryana/src/main.py", line 60, in <module>
   sendRechargeCongrats()
 File "/bbkinghome/nedmonds/Haryana/src/main.py", line 26, in sendRechargeCongrats
   SendRecharges.send_all_congrats(RSMS_handler, IVR_handler)
 File "/bbkinghome/nedmonds/Haryana/src/apiHandlers/SendRecharges.py", line 104, in send_all_congrats
   congrats_amount_to_phone_id_map)
 File "/bbkinghome/nedmonds/Haryana/src/apiHandlers/SendRecharges.py", line 39, in send_ivr_congrats_return_success_ids
   IVRMessages.get_code(ivr_type))
 File "/bbkinghome/nedmonds/Haryana/src/apiHandlers/VBHandler.py", line 36, in send_voice_calls
   return requests.get(self.voice_call_url, send_voice_calls_params).text
 File "/bbkinghome/nedmonds/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
   return request('get', url, params=params, **kwargs)
 File "/bbkinghome/nedmonds/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
   return session.request(method=method, url=url, **kwargs)
 File "/bbkinghome/nedmonds/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
   resp = self.send(prep, **send_kwargs)
 File "/bbkinghome/nedmonds/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
   r = adapter.send(request, **kwargs)
 File "/bbkinghome/nedmonds/.local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
   raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='transvoice.routemobile.com', port=80): Max retries exceeded with url: /httpApi/genCalls.php?dest=9467274779%2C8059374987%2C9466560863%2C9896509234&msg=53_0.88217500_1481924772&pwd=VidhiTPK&user=jpalt&jobType=http-audio (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x4a944d0>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by francineloza** [comment]
Problem narrowed down to IVR account on routesms- commented out the IVR method for now- Vidhi reached out, sticking to SMS for now.
