### ISSUE TITLE
Congrats Bug

### ISSUE THREAD

**Issue by francineloza** [francineloza/HIM_Operations#93]
sending congrats
staring round of congrats
Traceback (most recent call last):
 File "/bbkinghome/nedmonds/Haryana/src/main.py", line 60, in <module>
   sendRechargeCongrats()
 File "/bbkinghome/nedmonds/Haryana/src/main.py", line 26, in sendRechargeCongrats
   SendRecharges.send_all_congrats(RSMS_handler, IVR_handler)
 File "/bbkinghome/nedmonds/Haryana/src/apiHandlers/SendRecharges.py", line 96, in send_all_congrats
   congrats_amount_to_phone_id_map)
 File "/bbkinghome/nedmonds/Haryana/src/apiHandlers/SendRecharges.py", line 28, in send_sms_congrats_return_success_ids
   failed_ids += [phone_to_id_sub_map[x[0]] for x in fail_nums]
KeyError: u'38338127'

**Comment by francineloza** [comment]
Found problem: phone number starting with 91

TODO: Figure out what to do about this? temp fix? add exception? 

follow up on visit id: 
| 1496c4068c534d569c2c0af4dd7cb75f | None         | None         | 2017-03-10     | 2017-03-10      | PENDING           | PENDING           | FAILED          |

**Comment by francineloza** [comment]
resolved added  if len(phone_number)==12 to           if phone_number[0:2] == "91" :

TO DO: send this out in the morning
